"""
Per-module page content for the Airlogical marketing site.

Kept separate from build.py so the copy can grow without touching the
generator. Each module renders a genuinely distinct page — intro,
capabilities, how-it-works, who-it's-for and its own FAQs — rather than a
templated stub, which is what search engines need in order to index them
and what answer engines need in order to quote them.
"""

MODULES = [
    dict(
        slug="aircraft", name="Aircraft", color="#FAA52A",
        title="Aircraft Records & Airworthiness Software",
        kw="aircraft records software",
        lead="The Aircraft module is the record every other part of Airlogical hangs off — particulars, airworthiness status, documents and the daily dashboard for each tail.",
        intro=[
            "Every flight department needs one authoritative answer to a deceptively simple question: is this aircraft fit to fly today? Airlogical holds that answer in a single record per tail — the particulars, the airworthiness paperwork, the current serviceability status, and the documents that prove it.",
            "Because crew, trips, maintenance, certificates and costs all attach to that same record, nothing has to be reconciled between systems. Change an aircraft's status once and it propagates everywhere it matters: the fleet schedule, the pre-departure readiness check, and the compliance forecast.",
        ],
        capabilities=[
            ("Aircraft particulars", "Registration, ICAO type designator, serial number, home base and year built — the identity every other module references."),
            ("Airworthiness status", "Certificate of Registration and Airworthiness Review Certificate held with their expiry dates and surfaced in the compliance forecast well before they lapse."),
            ("Serviceability and AOG", "Mark an aircraft active, maintenance-due or grounded. A grounded tail is flagged across the fleet schedule and blocks the readiness check on any leg it's assigned to."),
            ("Operational category", "NCO, NCC, SPO or commercial. This drives which crew, medical and flight-time rules Airlogical applies to every leg on that aircraft."),
            ("Aircraft documents", "Insurance, noise and radio certificates, manuals and type paperwork, stored against the aircraft with version history."),
            ("The daily dashboard", "A per-aircraft view of what's due, expiring, open or awaiting sign-off — the screen the team opens first each morning."),
        ],
        how=[
            ("Create the aircraft", "Enter registration, type and operational category; Airlogical scaffolds the record and its default certificate structure."),
            ("Attach the paperwork", "Load the CofR, ARC, insurance and type documents. Expiry tracking starts the moment a date is entered."),
            ("Assign your crew", "Link crew profiles to the tail, with per-aircraft permissions controlling who sees and edits what."),
            ("Operate", "Trips, maintenance, costs and compliance all reference this record from here on — one source of truth."),
        ],
        who="Operators of private and business aircraft, from a single owner-flown aeroplane to a management company running a mixed fleet across several owners.",
        faqs=[
            ("What does the Aircraft module do?",
             "It holds each aircraft's particulars, airworthiness status and key documents, and provides the per-aircraft dashboard your flight department opens first to see what needs attention."),
            ("Does it track airworthiness and ARC expiry?",
             "Yes. The Certificate of Registration, Airworthiness Review Certificate and related expiries are tracked on the aircraft record and surfaced in the compliance forecast before they lapse."),
            ("Can I mark an aircraft as AOG or grounded?",
             "Yes. Setting an aircraft to grounded flags it across the fleet schedule and causes the pre-departure readiness check to block any leg assigned to it."),
            ("Why does operational category matter?",
             "Because NCO, NCC, SPO and commercial operations carry different crew, medical and flight-time requirements. Setting the category once means Airlogical applies the right rules to every leg automatically."),
            ("Does it support multiple aircraft and multiple owners?",
             "Yes. Airlogical is multi-aircraft and multi-owner by design, with strict separation so each owner only ever sees their own aircraft's data."),
        ],
        related=["certificates", "technical", "compliance"],
    ),
    dict(
        slug="crew", name="Crew", color="#B161CF",
        title="Aircraft Crew Management Software",
        kw="crew management software",
        lead="Airlogical is crew management software for aviation: profiles, licences and ratings, medicals, recency and currency, flight-time limitations and per-aircraft permissions — the complete crew record in one place.",
        intro=[
            "Keeping crew legal is a moving target. A licence is valid until it isn't; a medical lapses on a date; recency decays quietly with every week not flown; and duty limits shift with every trip. Tracked in a spreadsheet, these only surface when someone remembers to look.",
            "Airlogical holds the whole crew record — qualifications, medicals, recency and duty — and evaluates it automatically at the point it matters: when a crew member is assigned to a leg, and across the forward schedule so a problem is visible days before it becomes a delay.",
        ],
        capabilities=[
            ("Licences, ratings and type ratings", "Held with issue and expiry dates and validated against the aircraft type being flown, so an out-of-type or expired rating is caught before assignment."),
            ("Medicals", "Class 1, Class 2 and LAPL medicals tracked with expiry, and checked against the operational category — Class 1 where the operation requires it."),
            ("Recency and currency", "90-day landing recency derived from the legs actually flown, so a pilot who has quietly gone out of currency is flagged rather than assumed current."),
            ("Flight-time limitations (FTL)", "Duty periods and flight time recorded and evaluated against flight duty period, cumulative and rest requirements, with commander's-discretion recorded where used."),
            ("Crew documents", "Passports, visas, training records and certificates stored against the profile with expiry tracking."),
            ("Per-aircraft permissions", "Section-level access per aircraft — a pilot sees their own profile and trips; a manager sees the fleet."),
        ],
        how=[
            ("Build the profile", "Add the crew member with their position, base and contact details."),
            ("Load qualifications", "Enter licences, ratings, type ratings and medicals with their dates; expiry tracking begins immediately."),
            ("Assign to aircraft", "Link them to the tails they fly, with the permissions appropriate to their role."),
            ("Let it check itself", "From then on, every leg assignment and the fleet schedule are checked against their qualifications, recency and duty."),
        ],
        who="Flight departments and management companies who need to prove, at any moment, that the crew rostered to a flight were legal to operate it.",
        faqs=[
            ("How does Airlogical track flight-time limitations (FTL)?",
             "Airlogical records crew duty periods and flight time, then evaluates them against the applicable flight duty period, cumulative and rest limits. Crew approaching or exceeding a limit are flagged at the point of assignment and across the fleet schedule."),
            ("Does it track licence and medical expiry?",
             "Yes. Licences, ratings, type ratings and medicals are all held with expiry dates, checked against the aircraft and operation, and surfaced in the compliance forecast."),
            ("What is landing recency and how is it calculated?",
             "Landing recency is the requirement to have completed a minimum number of take-offs and landings in the preceding 90 days to carry passengers. Airlogical derives it from the legs a pilot actually operated, rather than relying on a manually maintained figure."),
            ("Can a pilot only see their own record?",
             "Yes. Permissions are section-level and per aircraft, so a pilot sees their own profile and assigned trips while managers see the fleet."),
            ("Does it handle crew across several aircraft?",
             "Yes. Crew can be assigned to multiple tails, and their qualifications are validated against whichever aircraft type a given leg is flown on."),
        ],
        related=["certificates", "operations", "compliance"],
    ),
    dict(
        slug="certificates", name="Certificates", color="#E7C948",
        title="Aircraft & Crew Certificate Tracking Software",
        kw="certificate tracking software",
        lead="Airlogical puts aircraft, crew and company certificates in one register with automatic expiry tracking, document storage and reminders — so nothing lapses by surprise.",
        intro=[
            "Most operators don't lose control of certificates through carelessness — they lose it through fragmentation. Aircraft paperwork sits with the technical team, crew licences with the chief pilot, company approvals with the office, and no single view shows what expires next month.",
            "Airlogical consolidates all three into one register. Every certificate carries its issue and expiry dates and the document itself, and everything that's approaching expiry rises to the top of a single ranked list.",
        ],
        capabilities=[
            ("One register, three scopes", "Aircraft, crew and company certificates in a single structure, so nothing depends on remembering which system holds what."),
            ("Configurable certificate types", "Define the certificate types your operation actually holds, organised into sections, rather than being forced into a fixed list."),
            ("Automatic expiry tracking", "Every certificate with a date is monitored and surfaced as due-soon or overdue without anyone running a report."),
            ("Document storage", "The certificate PDF or scan is held against the record, so evidence is one click away during an audit."),
            ("Reminders", "Upcoming expiries are pushed to the people responsible rather than waiting to be discovered."),
            ("Audit-ready views", "Filter to what's expired, expiring or complete, and export the picture an inspector asks for."),
        ],
        how=[
            ("Set up your types", "Configure the certificate types and sections that match your operation — done once."),
            ("Load the certificates", "Add each certificate with its dates and attach the document."),
            ("Watch the forecast", "Expiring items appear automatically in the compliance forecast, ranked by urgency."),
            ("Renew and replace", "Update the record on renewal; the history of previous versions is retained."),
        ],
        who="Any operator who has ever been asked \"when does that expire?\" and had to go looking in more than one place.",
        faqs=[
            ("What certificates can Airlogical track?",
             "Aircraft, crew and company certificates alike — from Certificates of Registration, ARCs and insurance through to crew licences, ratings and medicals — all in one register with expiry tracking."),
            ("Does it send expiry reminders?",
             "Yes. Certificates approaching expiry are surfaced in the compliance forecast and in reminders, so they can be renewed before they lapse rather than after."),
            ("Can I define my own certificate types?",
             "Yes. Certificate types and the sections they sit in are configurable, so the register reflects the certificates your operation actually holds."),
            ("Are the actual documents stored?",
             "Yes. The scan or PDF is stored against the certificate record, so the evidence is available immediately during an audit or oversight inspection."),
            ("What happens when a certificate is renewed?",
             "You update the record with the new dates and document; the previous version is retained so the history remains auditable."),
        ],
        related=["aircraft", "crew", "compliance"],
    ),
    dict(
        slug="operations", name="Operations", color="#3B82F6",
        title="Flight Operations & Trip Management Software",
        kw="flight operations software",
        lead="Airlogical manages every trip end to end — planning and dispatch, handling and permits, in-flight services, and a printable trip pack — with each leg checked for readiness before it flies.",
        intro=[
            "A trip is not one decision, it's dozens: which aircraft, which crew, which handler, which permits, what's on board, and whether every one of those is actually in place before the doors close. Most of those decisions are made in email and remembered in someone's head.",
            "Airlogical structures the trip as legs, attaches everything each leg needs, and — critically — evaluates whether the leg is ready to fly. The readiness check draws on the rest of the platform: aircraft status, crew eligibility and recency, flight-time limits, confirmed services and granted permits.",
        ],
        capabilities=[
            ("Trips and legs", "Build a trip from its legs, with route, scheduled times, purpose and status through the dispatch workflow."),
            ("Crew assignment with eligibility checks", "Assign PIC and SIC with type rating, medical, recency and leave validated at the moment of assignment — not discovered later."),
            ("Handling, permits and services", "Track the handling agent, overflight and landing permits, fuel and catering per leg, with confirmation status visible."),
            ("Pre-departure readiness", "A per-leg report across aircraft, crew, services, permits and FTL, resolving to ready, needs-attention or not-cleared."),
            ("Trip pack", "A printable PDF for the crew with the route, times, crew, services, permits and readiness state."),
            ("Timeline view", "The aircraft's forward legs at a glance for the dispatcher."),
        ],
        how=[
            ("Create the trip", "Add the trip and its legs with routes and scheduled times."),
            ("Assign crew", "Airlogical validates each assignment against type rating, medical, recency and leave as you make it."),
            ("Arrange the ground", "Add handling, permits, fuel and catering per leg and mark them confirmed as they come in."),
            ("Check and fly", "Review the readiness report, clear anything outstanding, and issue the trip pack to the crew."),
        ],
        who="Dispatchers, operations managers and owner-pilots who need the whole trip — and its legality — in one place rather than across a mailbox.",
        faqs=[
            ("What is trip management in Airlogical?",
             "It's the end-to-end handling of a trip: planning legs, assigning crew, arranging handling and permits, and producing a trip pack — with a readiness check that flags anything that would prevent a leg from flying."),
            ("Does it check crew eligibility for a leg?",
             "Yes. Each assignment is checked for type rating, medical validity, landing recency and approved leave, and each leg is checked for aircraft status, services, permits and flight-time limits."),
            ("What is the trip pack?",
             "A printable PDF for the crew containing the trip's legs, times, assigned crew, services, permits and the readiness position — everything needed for the flight in one document."),
            ("Can it stop a leg that isn't legal?",
             "The readiness check resolves each leg to ready, needs-attention or not-cleared, with blockers such as a missing PIC, an expired type rating or a grounded aircraft called out explicitly."),
            ("Does it handle permits and handling agents?",
             "Yes. Overflight and landing permits and handling arrangements are tracked per leg with their confirmation status, and unconfirmed items show in the readiness report."),
        ],
        related=["crew", "technical", "finance"],
    ),
    dict(
        slug="technical", name="Technical", color="#2FB37E",
        title="Aircraft Maintenance Tracking & AD Compliance Software",
        kw="aircraft maintenance tracking software",
        lead="Airlogical is the single source of truth for engineering: the maintenance log, life-limited components, the Airworthiness Directive compliance register and open defects.",
        intro=[
            "Airworthiness is a question of evidence. It isn't enough for the maintenance to have been done — you have to be able to show what was done, when, against which directive, and what remains open. That evidence is what a ramp check or an oversight audit actually asks for.",
            "Airlogical keeps the maintenance record and the compliance evidence together: tasks and their due points, components and their remaining life, directives and how they were complied with, and defects with their deferral status.",
        ],
        capabilities=[
            ("Maintenance log", "Scheduled and unscheduled maintenance recorded against the aircraft, with what was done and when."),
            ("Maintenance programme", "Tasks with their due points by hours, cycles or calendar, so what's next is never a calculation someone does by hand."),
            ("Life-limited components", "Components tracked against their limits with remaining life visible, so replacement is planned rather than discovered."),
            ("Airworthiness Directive register", "AD compliance recorded per aircraft — which apply, how they were complied with, and what remains open."),
            ("Defects and deferrals", "Open defects logged, with deferred items and their MEL category and expiry tracked to closure."),
            ("Equipment and inventory", "The equipment fitted to the aircraft and the parts held, so an AOG isn't the first time you check stock."),
        ],
        how=[
            ("Load the programme", "Set up the maintenance tasks and their due points for the aircraft."),
            ("Record the work", "Log maintenance as it's carried out, against the task and the aircraft."),
            ("Track the evidence", "Record AD compliance and component life as part of the same record."),
            ("Manage what's open", "Defects and deferrals stay visible until closed, and due items surface in the compliance forecast."),
        ],
        who="Engineering and technical managers, and the operations team who need to know whether a maintenance item is about to take an aircraft out of service.",
        faqs=[
            ("Does Airlogical track Airworthiness Directives?",
             "Yes. Airlogical maintains an AD compliance register per aircraft, so you can show which directives apply, how each was complied with, and what remains open."),
            ("Can it track life-limited components?",
             "Yes. Life-limited components are held with their limits and remaining life, so replacements are planned ahead rather than discovered at inspection."),
            ("How are defects and MEL deferrals handled?",
             "Defects are logged against the aircraft and tracked to closure. Deferred defects carry their category and deferral expiry, so nothing is deferred indefinitely by accident."),
            ("Does maintenance status affect flight operations?",
             "Yes. An aircraft that is grounded or maintenance-due is flagged on the fleet schedule and in the pre-departure readiness check for any leg assigned to it."),
            ("Does it replace a dedicated maintenance tracking system?",
             "For many private and business operators, yes — the maintenance log, component life and AD register cover the need. It is deliberately lighter than a heavy CAMO-grade system."),
        ],
        related=["aircraft", "compliance", "operations"],
    ),
    dict(
        slug="safety", name="Safety", color="#E2453C",
        title="Aviation SMS Software (Safety Management System)",
        kw="aviation SMS software",
        lead="Airlogical is an aviation safety management system crew actually use — report forms, occurrence reports, hazards, risk assessments and corrective actions, all tracked to closure.",
        intro=[
            "Most safety management systems fail the same way: they are a folder of documents nobody opens and a reporting form nobody fills in. A system only works if reporting takes a minute and the loop visibly closes.",
            "Airlogical makes reporting quick from wherever crew are, then tracks each report through hazard identification, risk assessment and corrective action to closure — and keeps an audit-grade record of who acknowledged which manual revision and when.",
        ],
        capabilities=[
            ("Occurrence reporting", "Structured forms crew can complete quickly, with the detail an investigation actually needs."),
            ("Hazard log and risk assessments", "Identified hazards recorded and assessed, with mitigations captured against them."),
            ("Corrective actions", "Actions assigned, owned and tracked to closure rather than lost after the meeting."),
            ("Safety performance indicators", "A small set of fixed indicators so the picture is monitored, not merely reported."),
            ("Manuals and notices", "Controlled documents with revisions, published to crew with read-and-acknowledge."),
            ("Audit-grade acknowledgement trail", "Acknowledgement is recorded per crew member per manual revision — publishing a new revision requires fresh acknowledgement — and the register is exportable to CSV for an inspection."),
        ],
        how=[
            ("Publish your SMS documents", "Load the manual and safety notices; publishing a revision requests acknowledgement from the crew it targets."),
            ("Capture reports", "Crew submit occurrences and safety reports through structured forms."),
            ("Assess and act", "Log hazards, assess risk, and raise corrective actions with owners and due dates."),
            ("Close the loop and prove it", "Track actions to closure and export the acknowledgement register when an inspector asks."),
        ],
        who="Safety managers, accountable managers and any operator who needs to demonstrate a functioning SMS rather than merely possess one.",
        faqs=[
            ("What is an aviation SMS?",
             "A Safety Management System is the structured way an operator identifies hazards, reports occurrences and manages risk. Airlogical provides the forms, hazard log, risk assessments and corrective-action tracking that crew and safety managers use day to day."),
            ("Does it record who acknowledged a manual or notice?",
             "Yes. Read-and-acknowledge is tracked per crew member and per manual revision, with the date and time recorded, and the register can be exported to CSV."),
            ("What happens when a manual is revised?",
             "Publishing a new revision supersedes the previous one and requests fresh acknowledgement, so \"they acknowledged it\" always refers to the version actually in force."),
            ("Can we prove our SMS to an inspector?",
             "Yes. The occurrence records, hazard log, corrective actions and the exportable acknowledgement register together provide the evidence trail an oversight inspection asks for."),
            ("Do crew need a separate login to report?",
             "No. Crew use their normal Airlogical login, and reporting is available alongside their trips and documents."),
        ],
        related=["crew", "compliance", "operations"],
    ),
    dict(
        slug="finance", name="Finance", color="#3D5AC9",
        title="Aircraft Cost Tracking & Owner Statements Software",
        kw="aircraft cost tracking software",
        lead="Airlogical handles aircraft finance properly — standing costs, per-leg costs, budgets, pre-trip cost estimates and multi-currency owner statements — built for aviation rather than adapted from generic accounting.",
        intro=[
            "Aircraft cost reporting has a specific shape that general accounting software doesn't have: costs that belong to a leg, costs that accrue whether or not you fly, a management fee, and an owner who wants one clear statement rather than a general ledger.",
            "Airlogical models that shape directly — and adds the forward-looking half most operators lack: what a trip will cost before it flies, not only what it cost afterwards.",
        ],
        capabilities=[
            ("Standing costs", "Recurring costs — hangarage, insurance, subscriptions — with their cadence, prorated correctly into any reporting period."),
            ("Per-leg cost lines", "Variable costs attributed to the leg that incurred them, so trip cost is a fact rather than an allocation."),
            ("Pre-trip cost estimates", "An estimate before the trip flies, from the aircraft's hourly rate and estimated flight time plus optional positioning and handling allowances."),
            ("Budgets and variance", "Annual budgets per cost category compared against actuals, with the largest overruns surfaced first."),
            ("Multi-currency owner statements", "Statements produced in the base currency, with a versioned, supersede-aware workflow from draft to issued to acknowledged."),
            ("Owner portal", "A secure view for the owner — their aircraft, their statements, their costs — and nothing else."),
        ],
        how=[
            ("Set your rates", "Enter the base currency, hourly rate and any fixed allowances in finance settings."),
            ("Record costs", "Standing costs are entered once; per-leg costs attach to the legs as they're incurred."),
            ("Estimate before you fly", "Each trip shows its estimated cost, broken down by flight time and allowances."),
            ("Report to the owner", "Generate the statement for the period and share it through the owner portal."),
        ],
        who="Management companies reporting to aircraft owners, and owners who want to understand what their aircraft costs — before and after each trip.",
        faqs=[
            ("Can aircraft owners see their costs?",
             "Yes. Airlogical produces owner-grade statements and a secure owner portal, and shows a pre-trip cost estimate so owners can see what a trip will cost before it flies."),
            ("How is a trip cost estimated?",
             "From the aircraft's hourly rate multiplied by estimated flight time, plus optional fixed positioning and per-leg handling allowances. Legs without times are flagged so the total can't quietly under-count."),
            ("Is it multi-currency?",
             "Yes. Costs and owner statements support multiple currencies, with base-currency reporting for the operator."),
            ("How are recurring costs handled?",
             "Standing costs carry a cadence — monthly, quarterly, annual or one-off — and are prorated into whatever period you're reporting on."),
            ("Can a statement be corrected after it's issued?",
             "Statements are versioned. An issued statement is protected, and a correction supersedes it, so the history of what the owner was sent remains intact."),
        ],
        related=["operations", "aircraft", "compliance"],
    ),
    dict(
        slug="compliance", name="Compliance", color="#12A5CE",
        title="Aviation Compliance Software & Live Forecast",
        kw="aviation compliance software",
        lead="Airlogical gives you a single live forecast of everything coming due across every aircraft and crew member — certificates, checks, maintenance and training — ranked by what needs attention first.",
        intro=[
            "Compliance rarely fails because nobody knew the rule. It fails because the expiry was in a different system from the person who could act on it, and nobody looked in the right week.",
            "The Compliance module is Airlogical's answer: one forecast that reads from every other module — aircraft airworthiness, crew qualifications and recency, certificates, maintenance and training — and presents it as a single ranked list of what is overdue and what is due soon.",
        ],
        capabilities=[
            ("One forecast, whole fleet", "Every aircraft and every crew member in one view, rather than a report per module."),
            ("Ranked by urgency", "Overdue first, then due-soon, so the list is a work queue rather than a data dump."),
            ("Sourced from the live record", "The forecast reads the underlying records, so it can't drift out of date the way a manually maintained tracker does."),
            ("Permission-aware", "People see the aircraft and sections they're entitled to see, so the forecast is useful without over-sharing."),
            ("Surfaced where decisions happen", "The same compliance signals appear on the fleet schedule and in each leg's readiness check."),
            ("Exportable", "Take the position out as a report when an owner, auditor or authority asks for it."),
        ],
        how=[
            ("Keep the records current", "Certificates, qualifications and maintenance are maintained in their own modules as normal."),
            ("Let the forecast build itself", "Airlogical derives what's due from those records — no separate tracker to maintain."),
            ("Work the list", "Clear overdue and due-soon items in priority order."),
            ("Prove it", "Export the position for an audit or an owner report."),
        ],
        who="Accountable managers, compliance managers and owner-operators who need one answer to \"what's about to bite us?\" across the whole operation.",
        faqs=[
            ("What does the compliance forecast show?",
             "Everything coming due — certificate expiries, crew qualifications and recency, maintenance and training — across the whole fleet in one ranked list, so nothing expires by surprise."),
            ("Where does the forecast get its data?",
             "From the live records in the other modules. Because it derives rather than duplicates, it cannot drift out of date the way a separate spreadsheet tracker does."),
            ("Is it useful for audits?",
             "Yes. The forecast plus the underlying registers give an auditor a current picture and an exportable history of what happened and when."),
            ("Does everyone see everything?",
             "No. The forecast respects each person's permissions, so people see the aircraft and sections they're entitled to."),
            ("Does compliance affect dispatch?",
             "Yes. The same signals feed the fleet schedule and the pre-departure readiness check, so a compliance problem is visible at the point a leg is planned, not just in a report."),
        ],
        related=["certificates", "crew", "technical"],
    ),
]
